Change: Use data containers for feed sync
greenbone/docs pull request #174
Opened 2022-08-30 08:46 UTC by bjoernricks

**What**:

Introduce the new feed data containers for the Greenbone Community Containers

**Why**:

The data containers will improve and simplify the feed sync when using containers a lot.

**How**:

**Checklist**:

- [ ] Tests
- [ ] CHANGELOG.md entry
- [ ] Documentation

2022-08-30 09:12 UTC, k-schlosser requested changes

2022-08-30 09:12 UTC, k-schlosser commented on src/21.4/container/index.md
> +| dfn-cert-data | | A container that copies DFN-Cert data into the `cert_data_vol` volume on startup. Shows the license and exists afterwards. |
```suggestion
| dfn-cert-data | | A container that copies DFN-CERT data into the `cert_data_vol` volume on startup. Shows the license and exists afterwards. |
```

2022-08-30 09:12 UTC, k-schlosser commented on src/22.4/container/index.md
> +| dfn-cert-data | | A container that copies DFN-Cert data into the `cert_data_vol` volume on startup. Shows the license and exists afterwards. |
```suggestion
| dfn-cert-data | | A container that copies DFN-CERT data into the `cert_data_vol` volume on startup. Shows the license and exists afterwards. |
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/manual-feed-sync.md
> +Please be aware that the manual synced data will be overridden if the data
```suggestion
Please be aware that the manually synced data will be overridden if the data
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +## Update the Greenbone Community Containers
```suggestion
## Updating the Greenbone Community Containers
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/manual-feed-sync.md
> +## Manual Feed Sync
```suggestion
## Performing a Manual Feed Sync
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +2. The changes get loaded into memory and a database by a daemon
```suggestion
2. Loading the changes into memory and a database by a daemon
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +container images. When these images are started they copy the data into the used
```suggestion
container images. When these images are started, they copy the data into the used
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +daemons from the volumes.
```suggestion
docker volumes automatically. Afterwards, the data is picked up from the
volumes by the running daemons .
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +caption: Downloading the Greenbone Community Edition Feed Data Containers
```suggestion
caption: Downloading the Greenbone Community Edition feed data containers
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +caption: Starting the Greenbone Community Feed Data Containers
```suggestion
caption: Starting the Greenbone Community feed data containers
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +When feed content has been downloaded, the new data needs to be loaded by the
```suggestion
When feed content has been downloaded, the new data must be loaded by the
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +After the scanner is aware of the VT data, it will be requested by gvmd. This
```suggestion
After the scanner is aware of the VT data, the data will be requested by gvmd. This
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +##  Gain a Terminal for a Container
```suggestion
##  Gaining a Terminal for a Container
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +## Use gvm-tools for CLI access
```suggestion
## Using gvm-tools for CLI access
```

2022-08-30 09:12 UTC, k-schlosser commented on src/common/container/workflows.md
> +## Expose gvmd Unix socket for GMP access
```suggestion
## Exposing gvmd Unix socket for GMP Access
```

2022-08-31 06:26 UTC, y0urself approved these changes

2022-08-31 06:30 UTC, merged