Update cmake variables
greenbone/docs pull request #64
Opened 2022-01-17 16:27 UTC by ArnoStiefvater

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] CHANGELOG.md entry
- [ ] Documentation

2022-02-16 12:24 UTC, bjoernricks requested changes

2022-02-16 12:24 UTC, bjoernricks commented on src/common/gvmd/build.rst
>      -DGVM_RUN_DIR=/run/gvm \
```suggestion
```

2022-02-16 12:24 UTC, bjoernricks commented on src/common/gvm-libs/build.rst
> +    -DGVM_RUN_DIR=/run/gvm
IMHO the GVM_RUN_DIR can be removed completely. It should be obsolete with the next release.
```suggestion
```

2022-02-16 12:24 UTC, bjoernricks commented on src/common/gsa/build.rst
>      -DGVM_RUN_DIR=/run/gvm \
```suggestion
```

2022-02-16 12:24 UTC, bjoernricks commented on src/common/gsa/build.rst
>      -DGSAD_PID_DIR=/run/gvm \
```suggestion
    -DGSAD_PID_DIR=/run/gsad \
```

2022-03-30 06:56 UTC, bjoernricks commented
@ArnoStiefvater could you check if your changes have been already addressed?

2022-03-30 07:07 UTC, ArnoStiefvater commented
@bjoernricks Yes, will check this week or next monday. Thanks!

2022-04-04 17:57 UTC, ArnoStiefvater commented
I have checked and the issues indeed have been resolved. Thanks!

2022-04-04 17:57 UTC, closed without merging